action_id: trunk-single-player-auto-on-upgrade
date: 2023-08-20 16:42:06
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1692549726
full_timestamp:
  nanos: 466774000
  seconds: 1692549726
trunk_version: 1.14.0
