version: '3'

services:

    galhardo_ecommerce_pg:
        image: postgres
        container_name: galhardo_ecommerce_pg
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardo_ecommerce_network

    # POSTGRE username: postgres | password: root |server: galhardo_ecommerce_pg
    galhardo_ecommerce_adminer:
        image: adminer
        container_name: galhardo_ecommerce_adminer
        ports:
            - "9090:8080"
        networks:
            - galhardo_ecommerce_network

networks:
    galhardo_ecommerce_network:
        driver: bridge

volumes:
   postgres-data: null
