version: '3'

services:
    galhardo_app_pg:
        image: postgres
        container_name: galhardo_app_pg
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardo_app_network

    # POSTGRE username: postgres | password: root |server: galhardo_app_pg
    galhardo_app_adminer:
        image: adminer
        container_name: galhardo_app_adminer
        ports:
            - "9090:8080"
        networks:
            - galhardo_app_network

networks:
    galhardo_app_network:
        driver: bridge

volumes:
    postgres-data: null
