version: '3'

services:

    galhardoapp_pg:
        image: postgres
        container_name: galhardoapp_pg
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardoapp_network

    # POSTGRE username: postgres | password: root |server: galhardoapp_pg
    galhardoapp_adminer:
        image: adminer
        container_name: galhardoapp_adminer
        ports:
            - "8080:8080"
        networks:
            - galhardoapp_network

networks:
    galhardoapp_network:
        driver: bridge

volumes:
   postgres-data: null
