version: '3'

services:
    galhardo_ecommerce_postgres:
        image: postgres
        container_name: galhardo_ecommerce_postgres
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardo_ecommerce_network

    galhardo_ecommerce_rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        restart: always
        environment:
            - "RABBITMQ_DEFAULT_PASS=rabbitmq"
            - "RABBITMQ_DEFAULT_USER=rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - galhardo_ecommerce_network

networks:
    galhardo_ecommerce_network:
        driver: bridge

volumes:
    postgres-data: null
