action_id: trunk-share-with-everyone
date: 2023-08-20 16:42:03
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1692549723
full_timestamp:
  nanos: 182639000
  seconds: 1692549723
trunk_version: 1.14.0
